### ISSUE TITLE
Sunburst timestamp validation improvement

### ISSUE THREAD

**Issue by vbanos** [internetarchive/wayback-diff#29]
https://github.com/internetarchive/wayback-diff/blob/459210d5f19fa5a2ac822fdc6b593f9869f34e5c/src/components/sunburst-container.jsx#L59

Before showing the sunburst, we validate the target timestamp.
The way we do it currently is that we load the capture and if its successful, we conclude that the timestamp is valid.
This method is very inefficient, the capture could be really big, its not good trying to download it all.
Please perform a CDX query instead using the URL and timestamp to see if its valid.

Please also add a short comment in this function to explain its purpose.

**Comment by ftsalamp** [comment]
My first thought was to query the CDX server. The issue with that is that if the timestamp does not exist I have no way of knowing to which snapshot the WBM would redirect me to. I think I had asked you about this in the past and you told me that only the WBM decides/knows where to redirect the user to.

An alternative approach would be to query the CDX server and if the snapshot does not exist then get the snapshot from the WBM. The issue with this is that, as I have found while testing, the WBM and the CDX server have some kind of limit when it comes to how many requests they can accept per IP address per seconds/minute(s). This scenario is very likely to bring the user to an error page if they look at a couple diff pages.

Should I try the second approach and see how well it works?

**Comment by vbanos** [comment]
Another idea which I think is best considering what you told me about CDX limits is to use the availability API https://archive.org/help/wayback_api.php

Its a bit slower than CDX but its still good.

Please check the `timestamp` option, its exactly what you need.
